server.port: 8081
server.address: localhost
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
logging:
  level:
    sql: debug
doctor.specializations:
    specializations:
      - veterinarian
      - surgeon
      - geneticist

